#JWT secret
JWT_SECRET: myseecret

# Database
MYSQL_USERNAME: "YOUR USERNAME"
MYSQL_PASSWORD: "YOUR PASSWORD"
MYSQL_HOST: 192.168.1.44
MYSQL_PORT: 3306
MYSQL_DATABASE: invoice_project

#Server config
CONTAINER_PORT: 8089
ACTIVE_PROFILE: prod

#Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: "YOUR API EMAIL"
EMAIL_PASSWORD: "YOUR API KEY"
VERIFY_EMAIL_HOST: http://localhost:${8089}


#UI app url

UI_APP_URL: http://localhost:4200
