#JWT secret
JWT_SECRET: myseecret

# Database
MYSQL_USERNAME: root
MYSQL_PASSWORD: 1201991n
MYSQL_HOST: localhost
MYSQL_PORT: 3306
MYSQL_DATABASE: invoice_project

#Server config
CONTAINER_PORT: 8080
ACTIVE_PROFILE: dev

#Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: nikolalazin7@gmail.com
EMAIL_PASSWORD: khrflfxpfztuutcd
VERIFY_EMAIL_HOST: http://localhost:${CONTAINER_PORT}


#UI app url

UI_APP_URL: http://localhost:4200
